# Generated by Django 5.2.4 on 2025-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('cnpj_order', models.IntegerField()),
                ('cnpj_dv', models.IntegerField()),
                ('branch', models.BooleanField(blank=True, null=True)),
                ('trade_name', models.TextField(blank=True, null=True)),
                ('closing_date', models.IntegerField(blank=True, null=True)),
                ('opening_date', models.IntegerField(blank=True, null=True)),
                ('cep', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessFts',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('trade_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_fts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('corporate_name', models.TextField(blank=True, null=True)),
                ('capital', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('name_partner', models.TextField(blank=True, null=True)),
                ('start_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partners',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PartnersFts',
            fields=[
                ('rowid', models.IntegerField(primary_key=True, serialize=False)),
                ('name_partner', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'partners_fts',
                'managed': False,
            },
        ),
    ]
